# Generated by Django 4.2.16 on 2024-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataRecivedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempratureBody', models.CharField(max_length=64)),
            ],
        ),
    ]
