# Generated by Django 4.2.16 on 2024-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecivedmodel',
            name='heartRate',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='datarecivedmodel',
            name='humadity',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='datarecivedmodel',
            name='spo2',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='datarecivedmodel',
            name='temprature',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='datarecivedmodel',
            name='tempratureBody',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
