# Generated by Django 4.2.16 on 2024-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_datarecivedmodel_heartrate_datarecivedmodel_humadity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarecivedmodel',
            name='humadity',
        ),
        migrations.AddField(
            model_name='datarecivedmodel',
            name='humdity',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
