# Generated by Django 4.2.16 on 2024-12-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_datarecivedmodel_humadity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarecivedmodel',
            old_name='humdity',
            new_name='humidity',
        ),
    ]
